Updated per previous comments
However, I don't know what this error is that is causing Travis CI to fail???
```
Error: ../node/v7/index.d.ts: Definitions must use global references to other packages, not parent ("../xxx") references.(Based on reference 'base.d.ts')
```