Update @types/colors type definition for "bold"
Fix error caused by new TypeScript version:
```
node_modules/@types/colors/index.d.ts(118,9): error TS2717: Subsequent property declarations must have the same type.  Property 'bold' must be of type '() => string', but here has type 'string'.
```