layout extension for cytoscape-dagre extension
Adding interface to support cytoscape-dagre layout extension. As a fix for the following error,

error TS2322: Type '{ name: string; spacingFactor: number; nodeSep: number; edgeSep: number; rankSep: number; }' is not assignable to type 'LayoutOptions'.
  Object literal may only specify known properties, and 'nodeSep' does not exist in type 'LayoutOptions'.