Allow any type for AxiosTokenProvider.InterceptorOptions param of AxiosTokenProvider
Without the generic in the function declaration `AxiosTokenProvider.InterceptorOptions` defaults to `unknown` as the
generic type which causes type errors when attempting to type the options passed into the declared function.

error TS2345: Argument of type 'InterceptorOptions<TokenData>' is not assignable to parameter of type 'InterceptorOptions<unknown>'.
  Type 'unknown' is not assignable to type 'TokenData'.