Missing children property
Without "children" property, project does not compile, if SplitterLayout used in TSX files.

ERROR:
TS2322: Type '{ children: Element[]; vertical: boolean; primaryIndex: 1; percentage: true; secondaryInitialSize: number; onDragEnd: () => void; }' is not assignable to type 'IntrinsicAttributes & SplitterLayoutProps & RefAttributes<SplitterLayout>'.
Property 'children' does not exist on type 'IntrinsicAttributes & SplitterLayoutProps & RefAttributes<SplitterLayout>'.