Update in order to fix pty.js/pty.js.d.ts(23,18) error
Fix: pty.js/pty.js.d.ts(23,18): error TS2420: Class 'Terminal' incorrectly implements interface 'Stream'.
  Types of property 'addListener' are incompatible.