Updated Parameter Path from Array to String
getParametersByPathSync and getParametersByPath paramter path is accepting string instead of ParameterNameList type. 

It was giving below error when type was ParameterNameList
```
throw new Error( queryResult.err.message || queryResult.err.code );
                  ^
Error: Expected params.Path to be a string
```