import and use `Url` properly
currently imports a `URL` from 'url' library, except that `URL` does not exist; however `Url` does exist. 

Discovered upon trying to run tsc and getting the following error message: `node_modules/@types/nodemailer/lib/mailer/index.d.ts(6,10): error TS2305: Module '"url"' has no exported member 'URL'.`

As soon as I replaced `URL` with `Url` tsc correctly compiled.