Correct sub type of MuiThemeProviderProps
This will fix errors whereby

```
React.createElement(MuiThemeProvider, {
    muiTheme: lightMuiTheme,
    className: 'root',
});
```

would report

```
error TS2345: Argument of type '{ muiTheme: MuiTheme; className: string; }' is not assignable to parameter of type '(MuiThemeProviderProps & Attributes) | undefined'.
   Object literal may only specify known properties, and 'className' does not exist in type '(MuiThemeProviderProps & Attributes) | undefined'.
```