Set SocketIO.Server to extend EventEmitter
I am getting errors when trying to use `off` on the socket server listener. This is the part of the code that receives the type error:

```typescript
function watchForCancelledJobs() {
  const listener = function(jobId: string) {
    console.log({ type: "cancel-job", payload: { job: jobId } });
  };

  socket.on("cancel-job", listener);

  return () => {
    socket.off("cancel-job", listener); // Property 'off' does not exist on type 'Server'
  };
}
```

I believe the method comes from:
https://github.com/socketio/socket.io/blob/master/lib/socket.js#L81