Update index.d.ts
the `export as namespace ReduxActions;` is causing breakage in the newer renditions of typescript. The error now thrown is:

error TS1316: Global module exports may only appear at top level.