Update deep-diff.d.ts
Improvements compared to the current typings:

* Introduces and uses a DiffableObject<T> instead of a generic object, this allows VS Code to understand what the result of a function call to `diff` will be.
* Introduces a BaseDiff<T> interface which is extended for each kind of Diffs, this allows VS Code to perform control flow analysis in TypeScript >= 2.0.
* For ArrayDiff, the first item in the path array is a number
* Add descriptions for all functions and types

```typescript
import deepDiff from 'deep-diff';
// or import { diff as deepDiff } from 'deep-diff';

type landmark = { [id: string]: GeometricalObject } | { };

const diffs = deepDiff(
  this.props.landmarks,
  nextProps.landmarks
); // diffs is of type Diff<GeometricalObject>[];
if (diffs) {
  shouldRerender = true;
  diffs.forEach(diff => {
    // diff is of type Diff<GeometricalObject>
    if (diff.kind === 'N') {
      // diff is now of type NewDiff<GeometricalObject>
     // rhs is of type GeometricalObject;
      const object = geometricalObjectToFabricObject(diff.rhs, diff.path[0]);
      

      // Property lhs is undefined for diffs of kind N
      diff.lhs // Error: Property 'lhs' does not exist on type 'NewDiff<GeometricalObject>'
      if (object) {
        // diff.path is of type string[];
        objectMap.set(diff.path[0], object);
        landmarksGroup.add(object);
      }
    } else if (diff.kind === 'E') {
      // diff is of type EditDiff<GeometricalObject>
      // diff has properties: lhs, rhs
      objectMap.get(diff.path[0]).set(diff.path[1], diff.rhs);
    } else if (diff.kind === 'D') {
      // diff is of type DeleteDiff<GeometricalObject>
     // Property rhs is undefined for diffs of kind N
      diff.rhs // Error: Property 'rhs' does not exist on type 'NewDiff<GeometricalObject>'
      objectMap.get(diff.path[1]).remove();
      objectMap.delete(diff.path[0]);
    }  else if (diff.kind === 'A') {
        // diff is of type ArrayDiff<GeometricalObject>
        // diff has properties: index, item
        // diff.path[0] is of type number
        // diff.path[1] is of type string
     }
  });
```