[velocity-animate] Export a module so it can be used with "import".
The following code snippet would work nicely with the fix:

  import * as Velocity from 'velocity-animate';

  Velocity.animate(...);

Otherwise, TypeScript throws the following error:

  TS2307: Cannot find module 'velocity-animate'.