Attempts to fix remaining errors.
```
knex/knex-tests.ts(502,9): error TS2345: Argument of type '(names: string) => void' is not assignable to parameter of type '(value: string[]) => void | PromiseLike<void>'.
  Types of parameters 'names' and 'value' are incompatible.
    Type 'string' is not assignable to type 'string[]'.
knex/knex-tests.ts(522,4): error TS2339: Property 'bind' does not exist on type 'QueryBuilder'.
knex/knex-tests.ts(533,35): error TS2339: Property 'return' does not exist on type 'QueryBuilder'.
```

https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/119593429