Add customEditor property
Hi!

I was having this issue while using the library:

```
ERROR in [at-loader] frontend/src/components/modals/Upload.tsx:538:40
    TS2339: Property 'customEditor' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<TableHeaderColumnProps, ComponentState>>...'.
```

It seems it is missing from the Definition file, so I just added it :).

Hope it helps!