fix error TS2497
For import `import * as md5 from "blueimp-md5";` error occurs `This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.`.
Because `export as namespace md5;`  incorrect module declaration.  As a solution, replace this code with an empty declaration.