Fix `equal` function when passing in an array
For example, `expect([1, 2, 3]).to.equal([1, 2, 3])` previously would
give the compilation error:

> Argument of type 'number[]' is not assignable to parameter of type 'number'.