[@types/request] Lint fix.
I had two PRs merge close together that caused the build to fail.
- #22809 fixed a bug
- #22821 removed all the overrides from `tslint.json`
Unfortunately, the former ended up with a couple lint issues.
```
./types/request/index.d.ts
ERROR: 64:20  unified-signatures  This overload and the one on line 63
can be combined into one signature taking `string | RequiredUriUrl &
TOptions`.

./types/request/request-tests.ts
ERROR: 10:5   prefer-const        Identifier 'value' is never
reassigned; use 'const' instead of 'let'.
```