Fix using angular-mocks types with typescript 3.7.5
Importing these types into a typescript 3.7.5 project resulted in an exception from the typescript compiler.

```
.../node_modules/typescript/lib/tsc.js:78602
                throw e;
                ^

TypeError: Cannot read property 'get' of undefined
```

My hunch is that it was due to a clash between the `mock` namespace and the `mock` property on the IAngularStatic interface.  The IAngularStatic interface is exported from the angular types module as angular so you end up with a clash between `angular.mock` referring to the namespace in the angular-mocks index.d.ts and also referring to the IMockStatic interface. Splitting the angular-mocks `mock` namespace to `http` and `browser` for their respective interfaces fixes the problem for us.