Add state def arg to React.Component (#18694)
This removes the following errors for me:

```
node_modules/@types/victory/index.d.ts(81,43): error TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).
node_modules/@types/victory/index.d.ts(175,39): error TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).
node_modules/@types/victory/index.d.ts(227,43): error TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).
node_modules/@types/victory/index.d.ts(669,38): error TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).
node_modules/@types/victory/index.d.ts(853,38): error TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).
node_modules/@types/victory/index.d.ts(924,37): error TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).
node_modules/@types/victory/index.d.ts(1010,39): error TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).
node_modules/@types/victory/index.d.ts(1107,39): error TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).
node_modules/@types/victory/index.d.ts(1185,38): error TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).
node_modules/@types/victory/index.d.ts(1418,41): error TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).
node_modules/@types/victory/index.d.ts(1520,39): error TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).
node_modules/@types/victory/index.d.ts(1664,37): error TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).
```