Fix pdfjs-dist typings to use proper reflect lib dom
It was giving the following error
`ERROR in node_modules/@types/pdfjs-dist/index.d.ts(7,1): error TS1084: Invalid reference directive syntax.`

The regression was introduced in
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33558/commits/46096ba4f75f6c76d1ea20c02f93e9829508c77b#diff-21e9d6e91ee2c9204daebf0a94339b21R7

Signed-off-by: Radoslav Kirilov <rkirilow@gmail.com>