jest-environment-puppeteer - delete duplicate
Currently, I get errors when I try to build a project which contains these type definitions, and this is the error:

```console
../../node_modules/@types/jest-environment-puppeteer/index.d.ts:63:11 - error TS2649: Cannot augment module 'browser' with value exports because it resolves to a non-module entity.

63     const browser: Browser;
             ~~~~~~~


Found 1 error.
```

```console
Cannot augment module 'browser' with value exports because it resolves to a non-module entity.ts(2649)
```

version: `4.4.0`

I don't know if this is the correct fix! Please correct if needed