fix(react): Add key prop to React.Fragment
This adds the key prop to `React.Fragment`. Without it the following code:
```
 const arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

return (
  <div>
    {arr.map((item) => {
      return (
        <Fragment key={item}>
          <div>Item: {item}</div>
        </Fragment>
      );
    })}
  </div>
);
```
will generate a compiler error:
```
Property 'key' does not exist on type 'IntrinsicAttributes & { children?: ReactNode; }'
```

The `key` is an allowed value for `React.Fragment` - https://react.dev/reference/react/Fragment