Fix onRangeChange types from CalendarProps
The types declaration of onRangeChange function seem to be wrong: typescript returns error if I try to manipulate the returning range array like the following:
<BigCalendar
  onRangeChange={
    range => {
      range.map((v, k) => { ... }) // typescript error here
    }
  }
/>

Typescript error:
Property 'map' does not exist on type 'Date[] | { start: stringOrDate; end: stringOrDate; }'.
Property 'map' does not exist on type '{ start: stringOrDate; end: stringOrDate; }'.

Furthermore, if you look at the variables returned by the function with a spread operator, you'll get an array of 2 elements:
[0] => range: Date[]
[1] => view: View