Solved export error in index.d.ts
Please fill in this template.

- [X] Prefer to make your PR against the `types-2.0` branch.
- [X] The package does not provide its own types, and you can not add them.
- [X] Test the change in your own code.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If changing an existing definition:
- [X] Provide a URL to  documentation or source code which provides context for the suggested changes: There are no changes made to the API, only in how the module is exported. Thus no URL has been included as it's not relevant.
- [X] Increase the version number in the header if appropriate.

**Solution for error "error TS2694: Namespace 'angular' has no exported member 'gettext'.".
Module "angular" is now imported. The "angular.gettext" namespace declaration has been changed to instead extend the angular module.**