[prop-types] Run react/test/managedAttributes.tsx
```
react (prop-types)$ ../../node_modules/.bin/dtslint .
Error: /.../repos/DefinitelyTyped/types/react/test/managedAttributes.tsx:97:16
ERROR: 97:16   expect  TypeScript@next compile error:
JSX element type 'React.Fragment' does not have any construct or call signatures.
ERROR: 99:19   expect  TypeScript@next compile error:
JSX element type 'React.Fragment' does not have any construct or call signatures.
ERROR: 121:16  expect  TypeScript@next compile error:
JSX element type 'React.Fragment' does not have any construct or call signatures.

/.../repos/DefinitelyTyped/types/react/test/tsx.tsx:83:6
ERROR: 83:6    expect  TypeScript@next compile error:
JSX element type 'React.Fragment' does not have any construct or call signatures.
ERROR: 84:10   expect  TypeScript@next compile error:
JSX element type 'React.Fragment' does not have any construct or call signatures.
ERROR: 88:10   expect  TypeScript@next compile error:
JSX element type 'React.Fragment' does not have any construct or call signatures.
ERROR: 97:6    expect  TypeScript@next compile error:
JSX element type 'React.StrictMode' does not have any construct or call signatures.

    at /.../repos/DefinitelyTyped/node_modules/dtslint/bin/index.js:158:19
    at Generator.next (<anonymous>)
    at fulfilled (/.../repos/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)
    at <anonymous>
```