[types/@passport]: fix property 'x' does not exist on type 'User'
when getting properties from req.user returned after passport authentication, an error is thrown by TypeScript
**example this code:**
```
const { user: { accessToken, profile } } = req;
```
or
```
const { accessToken, profile } = req.user;
```
**will throw Error:**
```
TSError: ⨯ Unable to compile TypeScript:
file.ts:9:19 - error TS2339: Property 'accessToken' does not exist on type 'User'.
file.ts:9:32 - error TS2339: Property 'profile' does not exist on type 'User'.
```