Added non-specialized signature for slider(methodName, values) to avoid compiler error TS2154
Compiling with TS 0.9.1.1 the compiler stopped with "error TS2154: Specialized overload signature is not subtype of any non-specialized signature."
As a matter of fact the non-specialized signature for the slider(methodName, values) overload was missing.
Adding it everything was fine.