[mocha] remove `console` type
`Base.consoleLog` was added in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70495

However, this breaks in environments missing `dom` or `node` types:

```
npm ERR! ../../node_modules/@types/mocha/index.d.ts:775:39 - error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
npm ERR!
npm ERR! 775             static consoleLog: typeof console.log;
npm ERR!                                           ~~~~~~~
```

This change replaces the inferred type with the trivial underlying
definition, so there's no reliance on the global `console` being
present.