I have no idea if this is correct or not because I have no idea why Braintree Client adds methods to the Client.prototype after it is instantiated. I'm just trying to figure out why I and others have so many problems with Braintree throwing errors such as `TypeError: client.getVersion is not a function`                                                                                                                                                                                                                                                                   `