Update index.d.ts
Fixes:

>ERROR in ...\node_modules\@types\react-router-redux\index.d.ts
(27,45): error TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).