test: add test for antlr4.tree resolution
This test requires importing `antlr4` itself, not destructured:

```ts
import * as antlr4 from 'antlr4';

export default class ExcelVisitor extends antlr4.tree.ParseTreeVisitor {}
```

whereas the existing tests assume a destructuring import:

```ts
import { Interval, InputStream, CommonTokenStream, Lexer, Parser, ParserRuleContext } from 'antlr4';
```

so this commit just adds the above `import * as` line, and that makes `npm run
test antlr4` fail with this:

```
Error: /Users/gthb/git/DefinitelyTyped/types/antlr4/antlr4-tests.ts:2:1
ERROR: 2:1  no-duplicate-imports  Multiple imports from 'antlr4' can be combined into one.
```

... which does not appear to be true (or at least I can't find a way to combine
these imports that works). Still committing in the current form to leave a
clear separation of steps in commit history and show test failures in the PR
history. Then a subsequent commit will replace the destructuring import with a
whole-module import and update references in existing tests.