Added missing DocumentFragment to jsdom definition
`error TS2304: Cannot find name 'DocumentFragment'.` is thrown when compiling in tsc without the `"dom"` library.