Improve typing of makeAsyncSelect.
Improve typing of `makeAsyncSelect`, before change I wasn't able to properly use `makeAsyncSelect` decorator function because of 
TS error `error TS2604: JSX element type 'NAME' does not have any construct or call signatures.`, also props from `SelectComponent` wasn't inferred.